name: qt
dependencies:
- anaconda-client=1.2.2=py35_0
- jupyter=1.0.0=py35_1
- matplotlib=1.5.1=np110py35_0
- networkx=1.11=py35_0
- numpy=1.10.2=py35_0
- pillow=3.1.0=py35_0
- pip=8.0.2=py35_0
- python=3.5.1=0
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- scikit-image=0.11.3=np110py35_0
- scikit-learn=0.17=np110py35_1
- scipy=0.16.1=np110py35_0
- setuptools=19.6.2=py35_0
- six=1.10.0=py35_0
- http://conda.anaconda.org/spyder-ide
  - pyqt5-5.5.0-py35_0.tar.bz2
- pip:
  - line-profiler==1.0
  - memory-profiler==0.41

