name: qt
dependencies:
- anaconda-client=1.2.2=py35_0
- appnope=0.1.0=py35_0
- clyent=1.2.0=py35_0
- cycler=0.9.0=py35_0
- decorator=4.0.6=py35_0
- freetype=2.5.5=0
- icu=56.1=0
- ipykernel=4.2.2=py35_0
- ipython=4.0.3=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jbig=2.1=0
- jinja2=2.8=py35_0
- jpeg=8d=1
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_1
- jupyter_client=4.1.1=py35_0
- jupyter_console=4.1.0=py35_0
- jupyter_core=4.0.6=py35_0
- libpng=1.6.17=0
- libtiff=4.0.6=1
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.1=py35_0
- nbconvert=4.1.0=py35_0
- nbformat=4.0.1=py35_0
- networkx=1.11=py35_0
- notebook=4.1.0=py35_0
- numpy=1.10.2=py35_0
- openssl=1.0.2f=0
- path.py=8.1.2=py35_1
- pexpect=3.3=py35_0
- pickleshare=0.5=py35_0
- pillow=3.1.0=py35_0
- pip=8.0.2=py35_0
- ptyprocess=0.5=py35_0
- pygments=2.1=py35_0
- pyparsing=2.0.3=py35_0
- pyqt5=5.5.0=py35_0
- python=3.5.1=0
- python-dateutil=2.4.2=py35_0
- python.app=1.2=py35_4
- pytz=2015.7=py35_0
- pyyaml=3.11=py35_1
- pyzmq=15.2.0=py35_0
- qt5=5.5.0=0
- qtconsole=4.1.1=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- scikit-image=0.11.3=np110py35_0
- scikit-learn=0.17=np110py35_1
- scipy=0.16.1=np110py35_0
- setuptools=19.6.2=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- tornado=4.3=py35_0
- traitlets=4.1.0=py35_0
- wheel=0.26.0=py35_1
- xz=5.0.5=0
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.1.1
  - jupyter-console==4.1.0
  - jupyter-core==4.0.6
  - line-profiler==1.0
  - memory-profiler==0.41

